spring:
  application:
    name: qa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2
